Instance: slate01

Service:
  Port: 1094
  ExternalIP: 129.107.255.46

SiteConfig:
  Name: SWT2

Monitoring:
  Collector: http://xcache.atlas-ml.org:80
  GStreamCollector: collector.atlas-ml.org:9000
  VPheartbeat: https://vps.cern.ch/liveness
XCacheConfig:
  # Local directory to be used as a cache. Forced restart 1.
  CacheDirectories:
    - path: /cache/disk_0
    - path: /cache/disk_1
    - path: /cache/disk_2
    - path: /cache/disk_3
    - path: /cache/disk_4
    - path: /cache/disk_5
    - path: /cache/disk_6
    - path: /cache/disk_7
    - path: /cache/disk_8
    - path: /cache/disk_9
    - path: /cache/disk_10
  MetaDirectory: /cache/metadata
  # Space usage
  HighWaterMark: 0.95
  LowWaterMark: 0.90

  # The amount of memory XCache is allowed to use (in GB)
  RamSize: 60g
  # Minimal chunk size that will be prefetched/cached.
  BlockSize: 256k
  # to prefetch even chunks that were not requested
  Prefetch: 0
  # The name of the secret that was created for your XCache certificate
  # This must be created BEFORE deploying XCache
  CertSecret: xcache-cert-secret

image:
  repository: hub.opensciencegrid.org/usatlas/atlas-xcache
  # repository: ivukotic/atlas-xcache
  tag: latest
  pullPolicy: Always
