Instance: slate01

Service:
  Port: 1094
  ExternalIP: 192.5.207.190

SiteConfig:
  Name: NET2

Monitoring:
  Collector: http://xcache.atlas-ml.org:80
  GStreamCollector: collector.atlas-ml.org:9000
  VPheartbeat: https://vps.cern.ch/liveness
XCacheConfig:
  CacheDirectories:
    - path: /scratch/disk/sdr
    - path: /scratch/disk/sdx
    - path: /scratch/disk/sdu
    - path: /scratch/disk/sdw
    - path: /scratch/disk/sdv
    - path: /scratch/disk/sdc
    - path: /scratch/disk/sdm
    - path: /scratch/disk/sdq
    - path: /scratch/disk/sdp
    - path: /scratch/disk/sdt
    - path: /scratch/disk/sdo
    - path: /scratch/disk/sdk
    - path: /scratch/disk/sdl
    - path: /scratch/disk/sdf
    - path: /scratch/disk/sds
    - path: /scratch/disk/sde
    - path: /scratch/disk/sdd
    - path: /scratch/disk/sdg
    - path: /scratch/disk/sdh
    - path: /scratch/disk/sdj
    - path: /scratch/disk/sdi
    - path: /scratch/disk/sdn
    - path: /scratch/disk/sdb
  MetaDirectory: /scratch/meta
  # Space usage
  HighWaterMark: 0.95
  LowWaterMark: 0.90

  # The amount of memory XCache is allowed to use (in GB)
  RamSize: 60g
  # Minimal chunk size that will be prefetched/cached.
  BlockSize: 256k
  # to prefetch even chunks that were not requested
  Prefetch: 0
  # The name of the secret that was created for your XCache certificate
  # This must be created BEFORE deploying XCache
  CertSecret: xcache-cert-secret

image:
  repository: hub.opensciencegrid.org/usatlas/atlas-xcache
  # repository: ivukotic/atlas-xcache
  tag: latest
  pullPolicy: Always
