Instance: slate02

Service:
  Port: 1094
  ExternalIP: 192.170.227.156

SiteConfig:
  Name: MWT2

Monitoring:
  Collector: http://xcache.atlas-ml.org:80
  GStreamCollector: collector.atlas-ml.org:9000
  VPheartbeat: https://vps.cern.ch/liveness
XCacheConfig:
  # Local directory to be used as a cache
  CacheDirectories:
    - path: /scratch/1
    - path: /scratch/2
    - path: /scratch/3
    - path: /scratch/4
    - path: /scratch/5
    - path: /scratch/6
  MetaDirectory: /scratch/0
  # Space usage
  HighWaterMark: 0.95
  LowWaterMark: 0.90

  # The amount of memory XCache is allowed to use (in GB)
  RamSize: 60g
  # Minimal chunk size that will be prefetched/cached.
  BlockSize: 256k
  # to prefetch even chunks that were not requested
  Prefetch: 0
  # The name of the secret that was created for your XCache certificate
  # This must be created BEFORE deploying XCache
  CertSecret: xcache-cert-secret

image:
  repository: ivukotic/atlas-xcache
  tag: latest
  pullPolicy: Always
