name: SLATE Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    uses: slateci/github-actions/.github/workflows/slate-deployment.yml@v1
    with:
      mailgun_send_to: "lincolnb@uchicago.edu, ssthapa@uchicago.edu, usatlas-federatedops-l@lists.bnl.gov"
    secrets:
      mailgun_api_key: "${{ secrets.MAILGUN_API_KEY }}"
      slate_api_token: "${{ secrets.SLATE_API_TOKEN }}"
